"""Feature / event / text constants from mdr-c/Headphones.h."""

from __future__ import annotations

FALSE = 0
TRUE = 1

AVAILABILITY_UNKNOWN = 0
AVAILABILITY_UNAVAILABLE = 1
AVAILABILITY_AVAILABLE = 2

FEATURE_IDENTITY = 1
FEATURE_BATTERY_SINGLE = 2
FEATURE_BATTERY_LEFT_RIGHT = 3
FEATURE_BATTERY_CASE = 4
FEATURE_PLAYBACK_METADATA = 5
FEATURE_PLAYBACK_CONTROL = 6
FEATURE_PLAYBACK_VOLUME = 7
FEATURE_NOISE_CANCELLING = 8
FEATURE_AMBIENT_SOUND = 9
FEATURE_ADAPTIVE_AMBIENT_SOUND = 10
FEATURE_SPEAK_TO_CHAT = 11
FEATURE_LISTENING_MODE = 12
FEATURE_EQUALIZER = 13
FEATURE_DSEE = 14
FEATURE_PAIRED_DEVICE_MANAGEMENT = 15
FEATURE_PAIRING_MODE = 16
FEATURE_GENERAL_SETTINGS = 17
FEATURE_ASSIGNABLE_CONTROLS = 18
FEATURE_NOISE_CONTROL_BUTTON = 19
FEATURE_AUTO_POWER_OFF = 20
FEATURE_WEARING_DETECTION = 21
FEATURE_AUTO_PAUSE = 22
FEATURE_HEAD_GESTURE = 23
FEATURE_VOICE_GUIDANCE = 24
FEATURE_VOICE_GUIDANCE_VOLUME = 25
FEATURE_SHUTDOWN = 26
FEATURE_CONNECTION_MODE = 27
FEATURE_SAFE_LISTENING = 28

EVENT_NONE = 0
EVENT_IDENTITY_CHANGED = 1
EVENT_BATTERY_CHANGED = 2
EVENT_PLAYBACK_CHANGED = 3
EVENT_NOISE_CONTROL_CHANGED = 4
EVENT_SPEAK_TO_CHAT_CHANGED = 5
EVENT_LISTENING_MODE_CHANGED = 6
EVENT_EQUALIZER_CHANGED = 7
EVENT_PAIRED_DEVICES_CHANGED = 8
EVENT_PAIRING_CHANGED = 9
EVENT_GENERAL_SETTINGS_CHANGED = 10
EVENT_ASSIGNABLE_CONTROLS_CHANGED = 11
EVENT_POWER_CHANGED = 12
EVENT_VOICE_GUIDANCE_CHANGED = 13
EVENT_CONNECTION_MODE_CHANGED = 14
EVENT_SAFE_LISTENING_CHANGED = 15
EVENT_INITIALIZE_COMPLETE = 16
EVENT_SYNC_COMPLETE = 17
EVENT_APPLY_COMPLETE = 18
EVENT_ALERT = 19
EVENT_INTERACTION = 20
EVENT_DEVICE_MESSAGE = 21
EVENT_UNHANDLED = 22

TEXT_MODEL_NAME = 1
TEXT_UNIQUE_ID = 2
TEXT_FIRMWARE_VERSION = 3
TEXT_MODEL_SERIES = 4
TEXT_MODEL_COLOR = 5
TEXT_TRACK_TITLE = 6
TEXT_TRACK_ALBUM = 7
TEXT_TRACK_ARTIST = 8
TEXT_PAIRED_DEVICE_ID = 9
TEXT_PAIRED_DEVICE_NAME = 10
TEXT_GENERAL_SETTING_SUBJECT = 11
TEXT_GENERAL_SETTING_SUMMARY = 12
TEXT_LAST_ERROR = 13
TEXT_LAST_ALERT = 14
TEXT_LAST_INTERACTION = 15
TEXT_LAST_DEVICE_MESSAGE = 16

BATTERY_MAIN = 0
BATTERY_LEFT = 1
BATTERY_RIGHT = 2
BATTERY_CASE = 3

CHARGING_UNKNOWN = 0
CHARGING_NO = 1
CHARGING_YES = 2
CHARGING_COMPLETE = 3

NOISE_MODE_OFF = 0
NOISE_MODE_CANCELLING = 1
NOISE_MODE_AMBIENT = 2

NOISE_MODE_NAMES = {
    NOISE_MODE_OFF: "off",
    NOISE_MODE_CANCELLING: "cancelling",
    NOISE_MODE_AMBIENT: "ambient",
}

EVENT_NAMES = {
    EVENT_NONE: "none",
    EVENT_IDENTITY_CHANGED: "identity",
    EVENT_BATTERY_CHANGED: "battery",
    EVENT_PLAYBACK_CHANGED: "playback",
    EVENT_NOISE_CONTROL_CHANGED: "noise_control",
    EVENT_SPEAK_TO_CHAT_CHANGED: "speak_to_chat",
    EVENT_LISTENING_MODE_CHANGED: "listening",
    EVENT_EQUALIZER_CHANGED: "equalizer",
    EVENT_PAIRED_DEVICES_CHANGED: "paired_devices",
    EVENT_PAIRING_CHANGED: "pairing",
    EVENT_GENERAL_SETTINGS_CHANGED: "general_settings",
    EVENT_ASSIGNABLE_CONTROLS_CHANGED: "assignable_controls",
    EVENT_POWER_CHANGED: "power",
    EVENT_VOICE_GUIDANCE_CHANGED: "voice_guidance",
    EVENT_CONNECTION_MODE_CHANGED: "connection_mode",
    EVENT_SAFE_LISTENING_CHANGED: "safe_listening",
    EVENT_INITIALIZE_COMPLETE: "initialize_complete",
    EVENT_SYNC_COMPLETE: "sync_complete",
    EVENT_APPLY_COMPLETE: "apply_complete",
    EVENT_ALERT: "alert",
    EVENT_INTERACTION: "interaction",
    EVENT_DEVICE_MESSAGE: "device_message",
    EVENT_UNHANDLED: "unhandled",
}

BATTERY_PART_NAMES = {
    BATTERY_MAIN: "main",
    BATTERY_LEFT: "left",
    BATTERY_RIGHT: "right",
    BATTERY_CASE: "case",
}
