"""Feature / event / text constants from mdr-c/Headphones.h."""

from __future__ import annotations

FALSE = 0
TRUE = 1

# MDR protocol version (MDRProtocolVersion) passed to mdrHeadphonesCreate.
PROTOCOL_V1 = 1
PROTOCOL_V2 = 2

PROTOCOL_NAMES = {
    PROTOCOL_V1: "v1",
    PROTOCOL_V2: "v2",
}

AVAILABILITY_UNKNOWN = 0
AVAILABILITY_UNAVAILABLE = 1
AVAILABILITY_AVAILABLE = 2

FEATURE_IDENTITY = 1
FEATURE_BATTERY_SINGLE = 2
FEATURE_BATTERY_LEFT_RIGHT = 3
FEATURE_BATTERY_CASE = 4
FEATURE_PLAYBACK_METADATA = 5
FEATURE_PLAYBACK_CONTROL = 6
FEATURE_PLAYBACK_VOLUME = 7
FEATURE_NOISE_CANCELLING = 8
FEATURE_AMBIENT_SOUND = 9
FEATURE_ADAPTIVE_AMBIENT_SOUND = 10
FEATURE_SPEAK_TO_CHAT = 11
FEATURE_LISTENING_MODE = 12
FEATURE_EQUALIZER = 13
FEATURE_DSEE = 14
FEATURE_PAIRED_DEVICE_MANAGEMENT = 15
FEATURE_PAIRING_MODE = 16
FEATURE_GENERAL_SETTINGS = 17
FEATURE_ASSIGNABLE_CONTROLS = 18
FEATURE_NOISE_CONTROL_BUTTON = 19
FEATURE_AUTO_POWER_OFF = 20
FEATURE_WEARING_DETECTION = 21
FEATURE_AUTO_PAUSE = 22
FEATURE_HEAD_GESTURE = 23
FEATURE_VOICE_GUIDANCE = 24
FEATURE_VOICE_GUIDANCE_VOLUME = 25
FEATURE_SHUTDOWN = 26
FEATURE_CONNECTION_MODE = 27
FEATURE_SAFE_LISTENING = 28

EVENT_NONE = 0
EVENT_IDENTITY_CHANGED = 1
EVENT_BATTERY_CHANGED = 2
EVENT_PLAYBACK_CHANGED = 3
EVENT_NOISE_CONTROL_CHANGED = 4
EVENT_SPEAK_TO_CHAT_CHANGED = 5
EVENT_LISTENING_MODE_CHANGED = 6
EVENT_EQUALIZER_CHANGED = 7
EVENT_PAIRED_DEVICES_CHANGED = 8
EVENT_PAIRING_CHANGED = 9
EVENT_GENERAL_SETTINGS_CHANGED = 10
EVENT_ASSIGNABLE_CONTROLS_CHANGED = 11
EVENT_POWER_CHANGED = 12
EVENT_VOICE_GUIDANCE_CHANGED = 13
EVENT_CONNECTION_MODE_CHANGED = 14
EVENT_SAFE_LISTENING_CHANGED = 15
EVENT_INITIALIZE_COMPLETE = 16
EVENT_SYNC_COMPLETE = 17
EVENT_APPLY_COMPLETE = 18
EVENT_ALERT = 19
EVENT_INTERACTION = 20
EVENT_DEVICE_MESSAGE = 21
EVENT_UNHANDLED = 22

TEXT_MODEL_NAME = 1
TEXT_UNIQUE_ID = 2
TEXT_FIRMWARE_VERSION = 3
TEXT_MODEL_SERIES = 4
TEXT_MODEL_COLOR = 5
TEXT_TRACK_TITLE = 6
TEXT_TRACK_ALBUM = 7
TEXT_TRACK_ARTIST = 8
TEXT_PAIRED_DEVICE_ID = 9
TEXT_PAIRED_DEVICE_NAME = 10
TEXT_GENERAL_SETTING_SUBJECT = 11
TEXT_GENERAL_SETTING_SUMMARY = 12
TEXT_LAST_ERROR = 13
TEXT_LAST_ALERT = 14
TEXT_LAST_INTERACTION = 15
TEXT_LAST_DEVICE_MESSAGE = 16

PACKET_DIRECTION_RX = 0
PACKET_DIRECTION_TX = 1

AUDIO_CODEC_UNKNOWN = 0
AUDIO_CODEC_SBC = 1
AUDIO_CODEC_AAC = 2
AUDIO_CODEC_LDAC = 3
AUDIO_CODEC_APTX = 4
AUDIO_CODEC_APTX_HD = 5
AUDIO_CODEC_LC3 = 6
AUDIO_CODEC_OTHER = 255

BATTERY_MAIN = 0
BATTERY_LEFT = 1
BATTERY_RIGHT = 2
BATTERY_CASE = 3

CHARGING_UNKNOWN = 0
CHARGING_NO = 1
CHARGING_YES = 2
CHARGING_COMPLETE = 3

PLAYBACK_UNKNOWN = 0
PLAYBACK_STOPPED = 1
PLAYBACK_PLAYING = 2
PLAYBACK_PAUSED = 3

PLAYBACK_PLAY = 1
PLAYBACK_PAUSE = 2
PLAYBACK_NEXT = 3
PLAYBACK_PREVIOUS = 4

NOISE_MODE_OFF = 0
NOISE_MODE_CANCELLING = 1
NOISE_MODE_AMBIENT = 2

ADAPTIVE_SENSITIVITY_UNKNOWN = 0
ADAPTIVE_SENSITIVITY_LOW = 1
ADAPTIVE_SENSITIVITY_STANDARD = 2
ADAPTIVE_SENSITIVITY_HIGH = 3

NOISE_BUTTON_NONE = 0
NOISE_BUTTON_NOISE_AMBIENT_OFF = 1
NOISE_BUTTON_NOISE_AMBIENT = 2
NOISE_BUTTON_NOISE_OFF = 3
NOISE_BUTTON_AMBIENT_OFF = 4

SPEECH_SENSITIVITY_UNKNOWN = 0
SPEECH_SENSITIVITY_AUTO = 1
SPEECH_SENSITIVITY_LOW = 2
SPEECH_SENSITIVITY_HIGH = 3

SPEAK_TIMEOUT_UNKNOWN = 0
SPEAK_TIMEOUT_SHORT = 1
SPEAK_TIMEOUT_MEDIUM = 2
SPEAK_TIMEOUT_LONG = 3
SPEAK_TIMEOUT_MANUAL = 4

LISTENING_STANDARD = 0
LISTENING_BACKGROUND_MUSIC = 1
LISTENING_CINEMA = 2

ROOM_UNKNOWN = 0
ROOM_SMALL = 1
ROOM_MEDIUM = 2
ROOM_LARGE = 3

EQ_OFF = 0
EQ_ROCK = 1
EQ_POP = 2
EQ_JAZZ = 3
EQ_DANCE = 4
EQ_EDM = 5
EQ_R_AND_B_HIP_HOP = 6
EQ_ACOUSTIC = 7
EQ_BRIGHT = 8
EQ_EXCITED = 9
EQ_MELLOW = 10
EQ_RELAXED = 11
EQ_VOCAL = 12
EQ_TREBLE = 13
EQ_BASS = 14
EQ_SPEECH = 15
EQ_HEAVY = 16
EQ_CLEAR = 17
EQ_HARD = 18
EQ_SOFT = 19
EQ_GAMING = 20
EQ_FPS_1 = 21
EQ_FPS_2 = 22
EQ_FPS_3 = 23
EQ_CUSTOM = 24
EQ_USER_1 = 25
EQ_USER_2 = 26
EQ_USER_3 = 27
EQ_USER_4 = 28
EQ_USER_5 = 29
EQ_UNKNOWN = 255

DSEE_UNKNOWN = 0
DSEE_STANDARD = 1
DSEE_HX = 2
DSEE_HX_AI = 3
DSEE_ULTIMATE = 4

PAIRED_DEVICE_CONNECT = 1
PAIRED_DEVICE_DISCONNECT = 2
PAIRED_DEVICE_SELECT_PLAYBACK = 3
PAIRED_DEVICE_UNPAIR = 4

GENERAL_SETTING_UNKNOWN = 0
GENERAL_SETTING_BOOLEAN = 1

ASSIGNABLE_NONE = 0
ASSIGNABLE_PLAYBACK = 1
ASSIGNABLE_NOISE_CONTROL = 2
ASSIGNABLE_NOISE_CONTROL_QUICK_ACCESS = 3
ASSIGNABLE_TRACK_CONTROL = 4
ASSIGNABLE_VOICE_ASSISTANT = 5
ASSIGNABLE_QUICK_ACCESS = 6

WEARING_POWER_UNAVAILABLE = 0
WEARING_POWER_DISABLED = 1
WEARING_POWER_WHEN_REMOVED = 2

AUDIO_PRIORITY_UNKNOWN = 0
AUDIO_PRIORITY_QUALITY = 1
AUDIO_PRIORITY_STABILITY = 2

# Keep display metadata below hand-authored; ABI values above are overridden by
# the generated header-derived definitions.
from ._generated_constants import *  # noqa: E402,F403

NOISE_MODE_NAMES = {
    NOISE_MODE_OFF: "off",
    NOISE_MODE_CANCELLING: "cancelling",
    NOISE_MODE_AMBIENT: "ambient",
}

AUDIO_CODEC_NAMES = {
    AUDIO_CODEC_UNKNOWN: "Unknown",
    AUDIO_CODEC_SBC: "SBC",
    AUDIO_CODEC_AAC: "AAC",
    AUDIO_CODEC_LDAC: "LDAC",
    AUDIO_CODEC_APTX: "aptX",
    AUDIO_CODEC_APTX_HD: "aptX HD",
    AUDIO_CODEC_LC3: "LC3",
    AUDIO_CODEC_OTHER: "Other",
}

CHARGING_NAMES = {
    CHARGING_UNKNOWN: "unknown",
    CHARGING_NO: "not charging",
    CHARGING_YES: "charging",
    CHARGING_COMPLETE: "charged",
}

PLAYBACK_STATUS_NAMES = {
    PLAYBACK_UNKNOWN: "Unknown",
    PLAYBACK_STOPPED: "Stopped",
    PLAYBACK_PLAYING: "Playing",
    PLAYBACK_PAUSED: "Paused",
}

ADAPTIVE_SENSITIVITY_NAMES = {
    ADAPTIVE_SENSITIVITY_UNKNOWN: "Unknown",
    ADAPTIVE_SENSITIVITY_LOW: "Low",
    ADAPTIVE_SENSITIVITY_STANDARD: "Standard",
    ADAPTIVE_SENSITIVITY_HIGH: "High",
}

NOISE_BUTTON_NAMES = {
    NOISE_BUTTON_NONE: "None",
    NOISE_BUTTON_NOISE_AMBIENT_OFF: "NC / Ambient / Off",
    NOISE_BUTTON_NOISE_AMBIENT: "NC / Ambient",
    NOISE_BUTTON_NOISE_OFF: "NC / Off",
    NOISE_BUTTON_AMBIENT_OFF: "Ambient / Off",
}

SPEECH_SENSITIVITY_NAMES = {
    SPEECH_SENSITIVITY_UNKNOWN: "Unknown",
    SPEECH_SENSITIVITY_AUTO: "Auto",
    SPEECH_SENSITIVITY_LOW: "Low",
    SPEECH_SENSITIVITY_HIGH: "High",
}

SPEAK_TIMEOUT_NAMES = {
    SPEAK_TIMEOUT_UNKNOWN: "Unknown",
    SPEAK_TIMEOUT_SHORT: "Short",
    SPEAK_TIMEOUT_MEDIUM: "Medium",
    SPEAK_TIMEOUT_LONG: "Long",
    SPEAK_TIMEOUT_MANUAL: "Manual",
}

LISTENING_MODE_NAMES = {
    LISTENING_STANDARD: "Standard",
    LISTENING_BACKGROUND_MUSIC: "Background Music",
    LISTENING_CINEMA: "Cinema",
}

ROOM_SIZE_NAMES = {
    ROOM_UNKNOWN: "Unknown",
    ROOM_SMALL: "Small",
    ROOM_MEDIUM: "Medium",
    ROOM_LARGE: "Large",
}

EQUALIZER_PRESET_NAMES = {
    EQ_OFF: "Off",
    EQ_ROCK: "Rock",
    EQ_POP: "Pop",
    EQ_JAZZ: "Jazz",
    EQ_DANCE: "Dance",
    EQ_EDM: "EDM",
    EQ_R_AND_B_HIP_HOP: "R&B / Hip-Hop",
    EQ_ACOUSTIC: "Acoustic",
    EQ_BRIGHT: "Bright",
    EQ_EXCITED: "Excited",
    EQ_MELLOW: "Mellow",
    EQ_RELAXED: "Relaxed",
    EQ_VOCAL: "Vocal",
    EQ_TREBLE: "Treble",
    EQ_BASS: "Bass",
    EQ_SPEECH: "Speech",
    EQ_HEAVY: "Heavy",
    EQ_CLEAR: "Clear",
    EQ_HARD: "Hard",
    EQ_SOFT: "Soft",
    EQ_GAMING: "Gaming",
    EQ_FPS_1: "FPS 1",
    EQ_FPS_2: "FPS 2",
    EQ_FPS_3: "FPS 3",
    EQ_CUSTOM: "Custom",
    EQ_USER_1: "User 1",
    EQ_USER_2: "User 2",
    EQ_USER_3: "User 3",
    EQ_USER_4: "User 4",
    EQ_USER_5: "User 5",
    EQ_UNKNOWN: "Unknown",
}

DSEE_TYPE_NAMES = {
    DSEE_UNKNOWN: "DSEE",
    DSEE_STANDARD: "DSEE",
    DSEE_HX: "DSEE HX",
    DSEE_HX_AI: "DSEE HX AI",
    DSEE_ULTIMATE: "DSEE Extreme",
}

PAIRED_DEVICE_COMMAND_NAMES = {
    PAIRED_DEVICE_CONNECT: "Connect",
    PAIRED_DEVICE_DISCONNECT: "Disconnect",
    PAIRED_DEVICE_SELECT_PLAYBACK: "Set as playback",
    PAIRED_DEVICE_UNPAIR: "Unpair",
}

ASSIGNABLE_ACTION_NAMES = {
    ASSIGNABLE_NONE: "None",
    ASSIGNABLE_PLAYBACK: "Playback",
    ASSIGNABLE_NOISE_CONTROL: "Noise Control",
    ASSIGNABLE_NOISE_CONTROL_QUICK_ACCESS: "Noise Control + Quick Access",
    ASSIGNABLE_TRACK_CONTROL: "Track Control",
    ASSIGNABLE_VOICE_ASSISTANT: "Voice Assistant",
    ASSIGNABLE_QUICK_ACCESS: "Quick Access",
}

WEARING_POWER_NAMES = {
    WEARING_POWER_UNAVAILABLE: "Unavailable",
    WEARING_POWER_DISABLED: "Disabled",
    WEARING_POWER_WHEN_REMOVED: "Power off when removed",
}

AUDIO_PRIORITY_NAMES = {
    AUDIO_PRIORITY_UNKNOWN: "Unknown",
    AUDIO_PRIORITY_QUALITY: "Sound Quality",
    AUDIO_PRIORITY_STABILITY: "Connection Stability",
}

AVAILABILITY_NAMES = {
    AVAILABILITY_UNKNOWN: "unknown",
    AVAILABILITY_UNAVAILABLE: "unavailable",
    AVAILABILITY_AVAILABLE: "available",
}

#: Auto power-off values (minutes) offered by the Sony app. ``0`` means "never".
AUTO_POWER_OFF_CHOICES = (0, 5, 15, 30, 60, 180)

AUTO_POWER_OFF_NAMES = {
    0: "Never",
    5: "5 minutes",
    15: "15 minutes",
    30: "30 minutes",
    60: "60 minutes",
    180: "180 minutes",
}

#: Center frequency labels per band count, matching the Sony app.
EQUALIZER_BAND_LABELS = {
    5: ("400", "1k", "2.5k", "6.3k", "16k"),
    10: ("31", "63", "125", "250", "500", "1k", "2k", "4k", "8k", "16k"),
}

#: Inclusive ``(min, max)`` gain range per band count.
EQUALIZER_BAND_RANGE = {5: (-10, 10), 10: (-6, 6)}

FEATURE_NAMES = {
    FEATURE_IDENTITY: "Identity",
    FEATURE_BATTERY_SINGLE: "Battery (single)",
    FEATURE_BATTERY_LEFT_RIGHT: "Battery (left/right)",
    FEATURE_BATTERY_CASE: "Battery (case)",
    FEATURE_PLAYBACK_METADATA: "Playback metadata",
    FEATURE_PLAYBACK_CONTROL: "Playback control",
    FEATURE_PLAYBACK_VOLUME: "Playback volume",
    FEATURE_NOISE_CANCELLING: "Noise cancelling",
    FEATURE_AMBIENT_SOUND: "Ambient sound",
    FEATURE_ADAPTIVE_AMBIENT_SOUND: "Adaptive ambient sound",
    FEATURE_SPEAK_TO_CHAT: "Speak-to-chat",
    FEATURE_LISTENING_MODE: "Listening mode",
    FEATURE_EQUALIZER: "Equalizer",
    FEATURE_DSEE: "DSEE",
    FEATURE_PAIRED_DEVICE_MANAGEMENT: "Paired device management",
    FEATURE_PAIRING_MODE: "Pairing mode",
    FEATURE_GENERAL_SETTINGS: "General settings",
    FEATURE_ASSIGNABLE_CONTROLS: "Assignable controls",
    FEATURE_NOISE_CONTROL_BUTTON: "Noise control button",
    FEATURE_AUTO_POWER_OFF: "Auto power off",
    FEATURE_WEARING_DETECTION: "Wearing detection",
    FEATURE_AUTO_PAUSE: "Auto pause",
    FEATURE_HEAD_GESTURE: "Head gesture",
    FEATURE_VOICE_GUIDANCE: "Voice guidance",
    FEATURE_VOICE_GUIDANCE_VOLUME: "Voice guidance volume",
    FEATURE_SHUTDOWN: "Shutdown",
    FEATURE_CONNECTION_MODE: "Connection mode",
    FEATURE_SAFE_LISTENING: "Safe listening",
    FEATURE_SOURCE_SWITCH_CONTROL: "Source switch control",
}

EVENT_NAMES = {
    EVENT_NONE: "none",
    EVENT_IDENTITY_CHANGED: "identity",
    EVENT_BATTERY_CHANGED: "battery",
    EVENT_PLAYBACK_CHANGED: "playback",
    EVENT_NOISE_CONTROL_CHANGED: "noise_control",
    EVENT_SPEAK_TO_CHAT_CHANGED: "speak_to_chat",
    EVENT_LISTENING_MODE_CHANGED: "listening",
    EVENT_EQUALIZER_CHANGED: "equalizer",
    EVENT_PAIRED_DEVICES_CHANGED: "paired_devices",
    EVENT_PAIRING_CHANGED: "pairing",
    EVENT_GENERAL_SETTINGS_CHANGED: "general_settings",
    EVENT_ASSIGNABLE_CONTROLS_CHANGED: "assignable_controls",
    EVENT_POWER_CHANGED: "power",
    EVENT_VOICE_GUIDANCE_CHANGED: "voice_guidance",
    EVENT_CONNECTION_MODE_CHANGED: "connection_mode",
    EVENT_SAFE_LISTENING_CHANGED: "safe_listening",
    EVENT_INITIALIZE_COMPLETE: "initialize_complete",
    EVENT_SYNC_COMPLETE: "sync_complete",
    EVENT_APPLY_COMPLETE: "apply_complete",
    EVENT_ALERT: "alert",
    EVENT_INTERACTION: "interaction",
    EVENT_DEVICE_MESSAGE: "device_message",
    EVENT_UNHANDLED: "unhandled",
}

BATTERY_PART_NAMES = {
    BATTERY_MAIN: "main",
    BATTERY_LEFT: "left",
    BATTERY_RIGHT: "right",
    BATTERY_CASE: "case",
}
