#!/usr/bin/env python3
"""Generate the low-level ctypes binding from SonyHeadphonesClient's C ABI."""

from __future__ import annotations

import argparse
import ast
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED_NOTICE = """\
\"\"\"Generated from SonyHeadphonesClient's mdr-c headers.

Do not edit this file directly; run ``python tooling/generate_bindings.py``.
\"\"\"

from __future__ import annotations
"""

INTEGER_CTYPES = {
    "char": "c_char",
    "int": "c_int",
    "int8_t": "c_int8",
    "uint8_t": "c_uint8",
    "uint32_t": "c_uint32",
    "unsigned char": "c_uint8",
}


@dataclass(frozen=True)
class Field:
    name: str
    c_type: str
    array_size: int | None = None
    callback_args: tuple[str, ...] | None = None


@dataclass(frozen=True)
class Struct:
    name: str
    fields: tuple[Field, ...]


@dataclass(frozen=True)
class Function:
    name: str
    result: str
    arguments: tuple[str, ...]


def strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    return re.sub(r"//.*?$", "", source, flags=re.MULTILINE)


def split_arguments(arguments: str) -> list[str]:
    parts: list[str] = []
    start = 0
    depth = 0
    for index, char in enumerate(arguments):
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append(arguments[start:index].strip())
            start = index + 1
    tail = arguments[start:].strip()
    if tail and tail != "void":
        parts.append(tail)
    return parts


def parse_declaration(declaration: str) -> tuple[str, str, int | None]:
    declaration = " ".join(declaration.strip().split())
    match = re.fullmatch(r"(.+?)([A-Za-z_]\w*)\s*(?:\[\s*(\d+)\s*\])?", declaration)
    if not match:
        raise ValueError(f"unsupported declaration: {declaration!r}")
    c_type = match.group(1).strip()
    name = match.group(2)
    array_size = int(match.group(3)) if match.group(3) else None
    return c_type, name, array_size


def argument_type(declaration: str) -> str:
    c_type, _, array_size = parse_declaration(declaration)
    if array_size is not None:
        c_type += "*"
    return c_type


def parse_structs(source: str) -> list[Struct]:
    structs: list[Struct] = []
    pattern = re.compile(
        r"typedef\s+struct\s+(\w+)\s*\{(.*?)\}\s*(\w+)\s*;",
        flags=re.DOTALL,
    )
    for tag, body, typedef_name in pattern.findall(source):
        if tag != typedef_name:
            raise ValueError(f"struct tag {tag} does not match typedef {typedef_name}")
        fields: list[Field] = []
        for declaration in body.split(";"):
            declaration = declaration.strip()
            if not declaration:
                continue
            callback = re.fullmatch(r"(.+?)\(\s*\*(\w+)\s*\)\s*\((.*)\)", declaration, re.DOTALL)
            if callback:
                args = tuple(argument_type(arg) for arg in split_arguments(callback.group(3)))
                fields.append(
                    Field(
                        name=callback.group(2),
                        c_type=callback.group(1).strip(),
                        callback_args=args,
                    )
                )
                continue
            c_type, name, array_size = parse_declaration(declaration)
            fields.append(Field(name, c_type, array_size))
        structs.append(Struct(typedef_name, tuple(fields)))
    return structs


def parse_callbacks(source: str) -> list[Function]:
    callbacks: list[Function] = []
    pattern = re.compile(
        r"^typedef\s+([^;]+?)\(\s*\*(\w+)\s*\)\s*\((.*?)\)\s*;",
        flags=re.DOTALL | re.MULTILINE,
    )
    for result, name, arguments in pattern.findall(source):
        callbacks.append(
            Function(
                name,
                " ".join(result.split()),
                tuple(argument_type(arg) for arg in split_arguments(arguments)),
            )
        )
    return callbacks


def parse_functions(source: str) -> list[Function]:
    functions: list[Function] = []
    pattern = re.compile(
        r"^MDR_API[ \t]+(.+?)\s+(mdr\w+)\s*\((.*?)\)\s*;",
        flags=re.DOTALL | re.MULTILINE,
    )
    for result, name, arguments in pattern.findall(source):
        functions.append(
            Function(
                name,
                " ".join(result.split()),
                tuple(argument_type(arg) for arg in split_arguments(arguments)),
            )
        )
    return functions


def parse_integer_aliases(source: str) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for base, name in re.findall(
        r"typedef\s+(u?int(?:8|32)_t)\s+(MDR\w+)\s*;",
        source,
    ):
        aliases[name] = base
    return aliases


def parse_opaque_structs(source: str) -> set[str]:
    return set(re.findall(r"typedef\s+struct\s+(\w+)\s+\1\s*;", source))


def ctype_expression(
    c_type: str,
    aliases: dict[str, str],
    struct_names: set[str],
    opaque_structs: set[str],
) -> str:
    c_type = " ".join(c_type.replace("*", " * ").split())
    c_type = re.sub(r"\bconst\b", "", c_type)
    c_type = " ".join(c_type.split())
    pointer_count = c_type.split().count("*")
    base = c_type.replace("*", "").strip()

    if base == "void" and pointer_count == 0:
        return "None"
    if base == "void":
        expression = "c_void_p"
        pointer_count -= 1
    elif base == "char" and pointer_count:
        expression = "c_char_p"
        pointer_count -= 1
    elif base in opaque_structs and pointer_count:
        expression = "c_void_p"
        pointer_count -= 1
    elif base in aliases:
        expression = base
    elif base in INTEGER_CTYPES:
        expression = INTEGER_CTYPES[base]
    elif base in struct_names:
        expression = base
    elif base.startswith("MDR"):
        expression = base
    else:
        raise ValueError(f"unsupported C type: {c_type!r}")

    for _ in range(pointer_count):
        expression = f"POINTER({expression})"
    return expression


def callback_name(struct_name: str, field_name: str) -> str:
    return f"{struct_name}{field_name[0].upper()}{field_name[1:]}"


def render_api(headers: list[str]) -> str:
    source = strip_comments("\n".join(headers))
    aliases = parse_integer_aliases(source)
    structs = parse_structs(source)
    callbacks = parse_callbacks(source)
    functions = parse_functions(source)
    struct_names = {struct.name for struct in structs}
    opaque_structs = parse_opaque_structs(source)

    def ct(c_type: str) -> str:
        return ctype_expression(c_type, aliases, struct_names, opaque_structs)

    lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        "from ctypes import (",
        "    CFUNCTYPE,",
        "    POINTER,",
        "    Structure,",
        "    c_char,",
        "    c_char_p,",
        "    c_int,",
        "    c_int8,",
        "    c_uint32,",
        "    c_uint8,",
        "    c_void_p,",
        ")",
        "",
    ]
    for name, base in aliases.items():
        lines.append(f"{name} = {INTEGER_CTYPES[base]}")
    lines.append("")

    for struct in structs:
        lines.extend([f"class {struct.name}(Structure):", "    pass", ""])
        for field in struct.fields:
            if field.callback_args is not None:
                args = ", ".join(ct(arg) for arg in field.callback_args)
                suffix = f", {args}" if args else ""
                lines.append(
                    f"{callback_name(struct.name, field.name)} = "
                    f"CFUNCTYPE({ct(field.c_type)}{suffix})"
                )
        if any(field.callback_args is not None for field in struct.fields):
            lines.append("")
        lines.append(f"{struct.name}._fields_ = [")
        for field in struct.fields:
            if field.callback_args is not None:
                expression = callback_name(struct.name, field.name)
            else:
                expression = ct(field.c_type)
                if field.array_size is not None:
                    expression = f"{expression} * {field.array_size}"
            lines.append(f'    ("{field.name}", {expression}),')
        lines.extend(["]", ""])

    for callback in callbacks:
        args = ", ".join(ct(arg) for arg in callback.arguments)
        suffix = f", {args}" if args else ""
        lines.extend([f"{callback.name} = CFUNCTYPE({ct(callback.result)}{suffix})", ""])

    lines.extend(["", "def bind(lib: object) -> None:"])
    for function in functions:
        arguments = ", ".join(ct(arg) for arg in function.arguments)
        lines.append(f"    lib.{function.name}.argtypes = [{arguments}]")
        lines.append(f"    lib.{function.name}.restype = {ct(function.result)}")
    lines.append("")
    return "\n".join(lines)


def safe_integer(expression: str) -> int:
    expression = re.sub(r"(?<=\d)[uUlL]+\b", "", expression.strip())
    tree = ast.parse(expression, mode="eval")
    operators = {
        ast.BitOr: lambda left, right: left | right,
        ast.BitAnd: lambda left, right: left & right,
        ast.LShift: lambda left, right: left << right,
        ast.RShift: lambda left, right: left >> right,
        ast.Add: lambda left, right: left + right,
        ast.Sub: lambda left, right: left - right,
    }

    def evaluate(node: ast.AST) -> int:
        if isinstance(node, ast.Expression):
            return evaluate(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, int):
            return node.value
        if isinstance(node, ast.BinOp) and type(node.op) in operators:
            return operators[type(node.op)](evaluate(node.left), evaluate(node.right))
        raise ValueError(f"unsupported integer expression: {expression!r}")

    return evaluate(tree)


def macro_value(expression: str) -> int | str | None:
    expression = expression.strip()
    cast = re.fullmatch(r"\(\([A-Za-z_]\w*\)\s*(.+)\)", expression)
    if cast:
        expression = cast.group(1)
    if expression.startswith('"') and expression.endswith('"'):
        return ast.literal_eval(expression)
    try:
        return safe_integer(expression)
    except (SyntaxError, ValueError):
        return None


def parse_macros(source: str) -> list[tuple[str, int | str]]:
    macros: list[tuple[str, int | str]] = []
    for name, expression in re.findall(r"^#define\s+(MDR_\w+)\s+(.+)$", source, flags=re.MULTILINE):
        value = macro_value(expression)
        if value is not None:
            macros.append((name, value))
    return macros


def python_constant_name(c_name: str, *, results: bool = False) -> str:
    name = c_name.removeprefix("MDR_")
    if results:
        name = name.removeprefix("RESULT_")
    return name


def render_constants(source: str, *, results: bool = False) -> str:
    lines = [GENERATED_NOTICE.rstrip(), ""]
    for c_name, value in parse_macros(strip_comments(source)):
        name = python_constant_name(c_name, results=results)
        lines.append(f"{name} = {value!r}")
    lines.append("")
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"out of date: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"generated: {path}")
    return True


def default_source_root(repo_root: Path) -> Path:
    configured = os.environ.get("MDR_SOURCE_DIR")
    if configured:
        return Path(configured)
    return repo_root.parent / "SonyHeadphonesClient"


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=default_source_root(repo_root),
        help="SonyHeadphonesClient checkout (default: MDR_SOURCE_DIR or sibling checkout)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "libmdr" / "src" / "libmdr",
        help="libmdr Python package directory",
    )
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()

    include = args.source.resolve() / "libmdr" / "include" / "mdr-c"
    paths = [include / name for name in ("Base.h", "Connection.h", "Headphones.h")]
    missing = [path for path in paths if not path.is_file()]
    if missing:
        parser.error("missing mdr-c header(s): " + ", ".join(str(path) for path in missing))
    base, connection, headphones = [path.read_text(encoding="utf-8") for path in paths]

    outputs = {
        args.output / "_generated_api.py": render_api([base, connection, headphones]),
        args.output / "_generated_constants.py": render_constants(headphones),
        args.output / "_generated_result.py": render_constants(base, results=True),
    }
    return 0 if all(write_or_check(path, content, args.check) for path, content in outputs.items()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
